### ISSUE TITLE
Behavior of `$set_row_roles` changed

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3#1175]
```r
library(data.table)
library(mlr3oml)
library(mlr3)
library(mlr3pipelines)

oml = OMLData$new(42730)
data = oml$data

tsk = TaskRegr$new("communities_crime", data, target = "ViolentCrimesPerPop")
n = length(tsk$row_roles$use)
split = partition(tsk)
tsk$set_row_roles(split$train, add_to = "use")
length(tsk$row_roles$use) == length(split$train) + n
#> TRUE
```

Previously this did not cause duplicated ids. 

This was probably caused by: https://github.com/mlr-org/mlr3/commit/bb4dd8d3fa63d288f2123aa2cffbee7104a27d3c

**Comment by be-marc** [comment]
I'm writing this as a breaking change in the NEWS. The code was actually wrong before. `set_row_roles` only has the options `add_to` and `remove_from`. But `add_to` removed all ids from the `"use"` row role and then added the ids passed by it.

**Comment by be-marc** [comment]
Prior to https://github.com/mlr-org/mlr3/commit/bb4dd8d3fa63d288f2123aa2cffbee7104a27d3c, `task$set_row_roles(split$train, "use")`  silently dropped duplicated ids. In fact this call did not change the `"use"` set at all. The ids in `split$train` where silently dropped because they were already in `"use"`. Now mlr3 adds `split$train` to   `"use"`  and we get duplicated ids but this is the rights behavior.  I think https://github.com/mlr-org/mcboost/blame/93f4514549589a46011ac10775fb8fd426485bdc/vignettes/mcboost_basics_extensions.Rmd#L524 was an user error. The author should have used `$row_roles$use = split$train` instead.
