### ISSUE TITLE
rename Experiment to MLExperiment or MLRExperiment?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#12]
maybe a bit more concrete...

also remove score() type top-level-functions and just call e$score()

**Comment by jakob-r** [comment]
Aren't these two things completely unrelated? :thinking: Also I don't see an exported score function.

hmm... now we get into this namespace problem. If we have MLExperiment then it should also be MLRLearner? I am against those prefix solutions just to fight possible clashes because it will be either in-consequent or really tiring. It makes only sense for packages that are meant to be used with many other things (eg. stringi)

**Comment by mllg** [comment]
`train()`, `predict()` and `score()` have already been removed.

**Comment by berndbischl** [comment]
> `train()`, `predict()` and `score()` have already been removed.

ok

**Comment by berndbischl** [comment]
> hmm... now we get into this namespace problem. If we have MLExperiment then it should also be MLRLearner?

just to be clear: I am ***not*** advocating that we prefix stuff in general, that's stupid. what i want is short, but precise names. "Experiment" is not really precise. hence this issue.

(and sorry for conflating this with a separate thing)
