### ISSUE TITLE
syntax a bit complicated

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr3#16]
In my humble opinion the syntax is still a bit complicated, also besides the custom R6 classes. 

Compare the code: 
```
data("mtcars", package = "datasets")
b = BackendDataTable$new(data = mtcars[, 1:3])
task = TaskRegr$new(id = "cars", b, target = "mpg")
```
with 
```
data("mtcars", package = "datasets")
task = makeClassifTask(data = mtcars[, 1:3], target = "mpg")
```

The second one seems at the moment also more intuitive to me, how should I now, that I need the "new" function to create a new task... ;)

**Comment by jakob-r** [comment]
First we will do it the R6 way - it will be more complicated but more flexible. In the future there might be helper functions but not now.

**Comment by berndbischl** [comment]
> In the future there might be helper functions

not for what is discussed here. 
what you see above are 2 things:

a) how do i create an object --> R6 constructor. it is not our job, to help people who refuse to read what that means. (and actually: the old mlr was worse here! because it was LESS clear how an object was constructed. i just created a convention that these types of functions should start with "make"...)

b) creation of an backend. yes it is one line more, but now you can work with other stuff than dataframes. 
one extra line vs. totally cool new feature --> winner clear
