### ISSUE TITLE
Bug in expand_grid?

### ISSUE THREAD

**Issue by camsique** [mlr-org/mlr3#245]
It is possible to use custom resampling with the "resample" function. But the same custom resampling results in an error from "expand_grid" when attempted to use in an benchmark.

# Bug: Benchmark with Custom resampling
# task
task_boston = mlr_tasks$get("boston_housing")
task_boston$set_col_role(c("chas", "town"), new_roles = "label")
# learner
lrn.lm = mlr_learners$get("regr.lm")
# resampling definition
rdesc = mlr_resamplings$get("custom")
train_sets = list((1:200), (1:300), (1:400))
test_sets = list((201:301), (301:401), (401:501))
rdesc$instantiate(task_boston, train_sets, test_sets)

# resample experiment
r_e = mlr3::resample(task_boston, lrn.lm, rdesc)

# benchmark
rdesc$is_instantiated
design = expand_grid(tasks = task_boston, learners = lrn.lm, resamplings = rdesc)
Error: Resampling 'custom' may not be instantiated

> rdesc$is_instantiated
[1] TRUE

**Comment by mllg** [comment]
This has been (partly) addressed in 2e4fd57df48527b04db32376bc05b893a653b2c1. 

`benchmark()` now accepts instantiated resampling objects only, and `expand_grid()` works solely on uninstantiated resamplings. Otherwise, we would have to guess what the user intends to do. Note that the `design` is a regular `data.table()` and as such you have full flexibility. E.g., you can just `rbind()` an exhaustive design from `expand_grid()` with a manually created design.

See https://github.com/mlr-org/mlr3/commit/2e4fd57df48527b04db32376bc05b893a653b2c1#diff-2224b03311ed7d812bc683501d1c00e9R154 for an example of using `ResamplingCustom` in `benchmark()`.
