### ISSUE TITLE
testing framework

### ISSUE THREAD

**Issue by jangorecki** [mlr-org/mlr3#326]
Two things related to testing process.
- `testthat` is in Suggested package thus would be wise to escape it in [`tests/testthat.R`](https://github.com/mlr-org/mlr3/blob/master/tests/testthat.R) by wrapping into `requireNamespace`, so complete package check (but not necessarily tests) can be performed having installed only mandatory packages. This is not a strict requirement, but just good practice (nice example of such can be found in https://github.com/markvanderloo/tinytest/pull/5).
- `testthat` is relatively heavy dependency, although optional one, but still heavy. As one of the project goals is to be lightweight, you might consider using base R (for example `stopifnot`) or [tinytest](https://github.com/markvanderloo/tinytest) instead.

**Comment by mllg** [comment]
>   `testthat` is in Suggested package thus would be wise to escape it in [`tests/testthat.R`](https://github.com/mlr-org/mlr3/blob/master/tests/testthat.R) [](/mlr-org/mlr3/blob/HEAD@{2019-08-16T14:25:07Z}/tests/testthat.R) by wrapping into `requireNamespace`, so complete package check (but not necessarily tests) can be performed having installed only mandatory packages. This is not a strict requirement, but just good practice (nice example of such can be found in [markvanderloo/tinytest#5](https://github.com/markvanderloo/tinytest/pull/5)).

So the goal is to run R CMD check without running the tests? Can you give an example where this is useful?
Many examples would also need to be wrapped to make their execution conditional.

> `testthat` is relatively heavy dependency, although optional one, but still heavy. As one of the project goals is to be lightweight, you might consider using base R (for example `stopifnot`) or [tinytest](https://github.com/markvanderloo/tinytest) instead.

:+1:
I already started to support `tinytest` in `checkmate` (https://github.com/markvanderloo/tinytest/issues/22). However, some missing features block the transition to tinytest currently (https://github.com/markvanderloo/tinytest/issues/28, https://github.com/markvanderloo/tinytest/issues/29).

**Comment by jangorecki** [comment]
> Can you give an example where this is useful?

editing documentation
In general it is more a matter of aligning to best practices. There should be an extra pkg dependency relationship field to address packages that are mandatory only for tests. I raised related (to vignettes) issue on r-devel: https://stat.ethz.ch/pipermail/r-devel/2016-April/072531.html

and lack of such escape of suggested packages was commented by @eddelbuettel
> I consider that to be a bug in those 'many packages'.  It essentially takes
away the usefulness of having a Suggests: to provide a more fine-grained
dependency graph.

It doesn't cost anything the add `if (requireNamespace())` call in testthat.R. You can easily put `else` branch doing `else cat("package tests has been skipped due to missing X package\n")`. Then check will pass. If you want it to raise an exception then `else if (isTRUE(as.character(Sys.genenv("MY_CI")))) error("package required for tests not present, in this pipeline we expect it to be installed")` instead. Sounds unnecessarily complex, but that would be basically the most correct way to address issue and still have needed checks in place.

Great to see your feedback to tinytest!

**Comment by eddelbuettel** [comment]
@mllg  Can you give an example where setup / teardown are needed?   I have to say that I really like the "flow" and "feeling" of `tinytest` as I can test per package (source, and, importantly, installed!!), test file, test directory, ...   Some of those are supported by [tt.r from littler](https://github.com/eddelbuettel/littler/blob/master/inst/examples/tt.r).

I may be missing something but because each `tinytest` "file" really is a standalone "file" you can just do "whatever setup is needed" at the top, and clean at the bottom (and/or `on.exit()` maybe).   As @markvanderloo suggested in https://github.com/markvanderloo/tinytest/issues/28 you can also share setup functions in the directory and source'em.

**Comment by mllg** [comment]
> editing documentation
> In general it is more a matter of aligning to best practices. There should be an extra pkg dependency relationship field to address packages that are mandatory only for tests. I raised related (to vignettes) issue on r-devel: [stat.ethz.ch/pipermail/r-devel/2016-April/072531.html](https://stat.ethz.ch/pipermail/r-devel/2016-April/072531.html)
> 
> and lack of such escape of suggested packages was commented by @eddelbuettel

I guess I agree here, it would be nice to be able to further subdivide packages listed in Suggests.
However, as long as we are stuck with only Suggests, I wonder how to deal with examples which require additional packages. Of course I could `requireNamespace()` here, too. But this would (a) bloat the code, and (b) has to be done manually, as there is no automation in place that can check that I did not miss anything.

I will change the tests to skip if `testthat` is not installed, but I don't think that checking `mlr3` without all suggested packages installed will be feasible in the future.

**Comment by mllg** [comment]
> @mllg Can you give an example where setup / teardown are needed? I have to say that I really like the "flow" and "feeling" of `tinytest` as I can test per package (source, and, importantly, installed!!), test file, test directory, ... Some of those are supported by [tt.r from littler](https://github.com/eddelbuettel/littler/blob/master/inst/examples/tt.r) [](/eddelbuettel/littler/blob/HEAD@{2019-08-20T12:01:32Z}/inst/examples/tt.r)

For this very package, I change the verbosity of the logger and set options to warn in case of partial argument matching. These global state changes are done in `setup.R` and reset in `teardown.R`. Another example would be to open file or data base connections in `setup.R` and close them in `teardown.R`.

`tinytest` already handles options and environment variables, but probably cannot be extended to deal with loggers or connection handlers.

**Comment by eddelbuettel** [comment]
Sure. But right now you could drop a file `myutils.R` into `inst/tinytest/` and have each file `test*.R` commence with `if (file.exists("myutils.R")) { source("myutils.R"); mysetup(); }`.   Longer-term I have found @markvanderloo to be rather receptive to suggestions I made several of which have changed `tinytest` already.  I am sure there is scope for something cleaner than the hack above...

**Comment by eddelbuettel** [comment]
@mllg  BTW I have been trying to catch up on the "extension mechanism".  Do you have a use case / illustration somewhere?

**Comment by mllg** [comment]
> @mllg BTW I have been trying to catch up on the "extension mechanism". Do you have a use case / illustration somewhere?

Do you mean the custom expectations? I have many expectations for `testthat` in `checkmate` (https://mllg.github.io/checkmate/reference/) and want to port them to tinytest (actually, this is already done). 

For example, in https://github.com/mlr-org/mlr3/blob/master/tests/testthat/test_resample.R you can find a mix of testthat's expectations, checkmate's expectations (e.g., `expect_data_table()`) and expectations I've written for `mlr3` objects, e.g. `expect_resample_result()`.

The source for `expect_resample_result()` is placed in `inst/` so that packages extending `mlr3` can source the file:

* Source: https://github.com/mlr-org/mlr3/blob/master/inst/testthat/helper_expectations.R#L379
* Add-on package: https://github.com/mlr-org/mlr3survival/blob/master/tests/testthat/test_resample.R / https://github.com/mlr-org/mlr3survival/blob/master/tests/testthat/helper.R#L1


Does this help?

**Comment by eddelbuettel** [comment]
Somewhat.  I guess the idea is to carry this over as discussed in https://github.com/markvanderloo/tinytest/issues/22 (which I had been unaware of until now).
