### ISSUE TITLE
help pages of sugar functions should link to their main R6 object help pages

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr3#368]
e.g. `?tnr` should contain a link to  `?Tuner`, `?rsmp` to `?Resampling`, and so on.
 
related to #354

**Comment by berndbischl** [comment]
the issue seems incorrect, because mlr3 sugar alrady has these links?
?rsmp already links to ?Resampling

and ?tnr also links to "Tuner" ? 

@Coorsaa did you really read the help pages....?

**Comment by Coorsaa** [comment]
when I type in `?rsmp` I end up at the documentation of `mlr_sugar`

**Comment by mllg** [comment]
`rsmp` links to `mlr_sugar`, that's right. It is probably a matter of personal preference as these pages are linking each other, but these are the candidates:

1. `mlr_sugar` explaining all sugar functions
2. `Resampling` because we return an object of this class
3. `mlr_resamplings` because we basically interface this dictionary

**Comment by mllg** [comment]
> a) this is not visible in docs at all?

There was missing a `@family` tag. Added now.

**Comment by mllg** [comment]
Changed again, there is now a hint to `as.data.table(.)` for each implementation under "see also".

**Comment by mllg** [comment]
`@family` tag is removed again. This was confusing because the list is not exhaustive ... dynamically added objects (e.g., by other packages) would not pop up here.

**Comment by mllg** [comment]
Everything should be clearly visible now.
