### ISSUE TITLE
mlrhyperopt package for mlr3

### ISSUE THREAD

**Issue by KnutJaegersberg** [mlr-org/mlr3#408]
mlrhyperopt is my favorite way for using mlr, because most of the time it brings me straight to what i am interested in with very little code. mlrhyperopt also gives easy access to all innovative tuning strategies just by changing function arguments and a database of hyperparameters. having this would convince me to make the switch from mlr to mlr3. do you plan an mlrhyperopt pendant in mlr3?

**Comment by pat-s** [comment]
ping @jakob-r

**Comment by mllg** [comment]
We did not discuss porting mlrhyperopt to mlr3 (yet). However, we are currently looking into building a framework for automatic machine learning. This will be comparably more powerful: Instead of hyperparameter spaces for single learners, we are planning to provide hyperparameter spaces for (small) pipelines consisting of learners and some reasonable preprocessing steps.

I'll update here as soon as we have written something down.

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3tuningspaces is on CRAN now.
