### ISSUE TITLE
task constructors and re-instantiating tasks

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3#470]
- This is not directly related to `mlr3spatiotempcv`, but the first package where this occurs, so I'll try to discuss this here. While developing `mlr3pipelines` I came across the following issue.
If I, for example, want to set a different `target` for a given task, I would basically have to reconstruct the `Task`. Currently, I construct a task of `new_type` as follows:
```
  tsk = get(mlr_reflections$task_types[mlr_reflections$task_types$type == new_type, ]$task)
  newtsk = tsk$new(id = intask$id, backend = intask$backend, target = new_target)
  # copy col_roles & row_roles
```

This does not work with  `mlr3spatiotempcv` as `new_type` is now `classif` and constructs a `Classif` task but the task should be a `ClassifST` task. In addition additional fields for `TaskClassifST` (`crs`, `coordinate_names`)  are required.

It would also be very cool if I could just copy a fixed set of other fields in order to obtain a valid re-instantiation of a task.

Would be possible if we made the following changes:
- `coordinate_names` is an active binding, setting / getting the corresponding `col_role`.
- `crs` is an active binding to a `$crs` item in a list called `task_metadata` (this should be in `mlr3`).

I could then instantiate a new `TaskClassifST`, copy col_roles, row_roles and task_metadata and would then have a valid copy of the original task.
  

  

- Just FYI: `self$crs` is added twice in [TaskClassifST](https://github.com/mlr-org/mlr3spatiotempcv/blob/master/R/TaskClassifST.R)

**Comment by mb706** [comment]
![image](https://user-images.githubusercontent.com/15801081/78127831-23ae9280-7415-11ea-9d40-1f349b871469.png)

**Comment by mllg** [comment]
If you expect me to do something now, you have to explain the figure ;)

**Comment by mb706** [comment]
That figure was created during a call and I wanted to preserve it :D

The problem we may face in `mlr3pipelines` is that we want to convert between tasks. We may for example have a `PipeOpClassifToRegr` that converts (binary) classif-tasks to regr-tasks and inverts the predictions after modeling through thresholding. Now if someone comes along and creates objects that are almost-classif-tasks and almost-regr-tasks it would be nice if our pipeop could also work for that package without having to be adapted. I believe what we want here is something like a "functor" in haskell? 

@pfistfl's suggestion here is to have a contract about what fields of the task contain all the information that needs to be preserved. The problem is that there should still be the information about what constructor to call (`TaskRegr` if the input is `TaskClassif`, `TaskRegrST` if the input is `TaskClassifST` etc.). Maybe there should be a database in `mlr_reflections` for this, or maybe there is a nicer way to have functors without needing to specify where all the information in a Task is stored.

**Comment by pfistfl** [comment]
So currently, we would also need something like this in many places:
- target transform
- setting a new target
- imputing with a learner
- ...

It should maybe look like [convert_task](https://github.com/mlr-org/mlr3pipelines/blob/33661b8c6c26d3cc790c998f494159e473f4ef5a/R/PipeOpNewTarget.R)

This would require the following changes:

- A `Task` should only have a limited number of member variables:
  `col_roles`, `row_roles`, `properties`, `task_metadata`.
  All other info should go into `task_metadata`, accessible perhaps via active bindings.
  This ensures that reconstructed tasks can simply copy those fields and ensure a valid
  reconstruction of the task.
  This also needs to be documented.

- mlr3 implements a version of the `convert_task` function above, which allows to re-instantiate a 
  `Task` with a new `task_type`, `target` etc.
   The current version of `convert_task` can not convert from `TaskClassifST` to `TaskRegrST`,
   as the constructor can not be uniquely obtained from `mlr_reflections` via `task_type = "regr"`.

**Comment by pfistfl** [comment]
Additionally, we should export a function (that can be used within `convert_task`) that looks as follows:

```
convert_to_task(data, target, task_type)
```

This would then be used to cast a `data.table` to a `Task` safely without having to know the constructor for each type.

**Comment by pfistfl** [comment]
Is this stage aware? I.e. state determines what is executed? prediction like train
Is train stochastic? imputesample
Is predict stochastic? imputesample

**Comment by pat-s** [comment]
Flo and I had a meeting about this today. Summary:

- Class `Task` in {mlr3} could get a field `extra_args` (named list, by default empty) which stores all extra constructor arguments of tasks besides `id`, `backend` and `target`. This enables easy reconstruction of custom tasks via this named list by invoking the task_type and the given list.
- During construction, every task writes its extra arguments into this field which is then passed to `super$initialize`.
- Each custom task should have a unique `task_type` to make reconstruction / conversion easier/enable it in the first place. This means instead of defining a second "classif" type, tasks should create something unique like "classif_st". If we stay with the notation "<type>_<identifier>" this wont get messy. Then each task can be converted to its respective counterpart easily, i.e. `classif_st` -> `regr_st`.
- New `assert_extra_args()` which checks if `extra_args` is a named list and does not contain `id`, `backend` or `target`
- All of the above enables freedom when creating custom tasks, i.e. custom tasks can define/require custom arguments during construction. This is very important to ensure that valid tasks are created in the first place. For example, bad things happen if a `ClassifST` task is created without coordinates and then used for training.
- (optional): `mlr_reflections$task_types` could get a slot `extra_args` listing the `extra_args` of the given task

Practical example: `TaskClassif` would then have `extra_args = list(positive = <value>)`

@mllg
