### ISSUE TITLE
Example for using MBO with mlr3learners?

### ISSUE THREAD

**Issue by pabuta88** [mlr-org/mlr3#483]
Hi,

I started using mlr3 and in particular lightgbm in mlr3learners. I was wondering whether there exists an example of how to use it together with MBO similar to learners from mlr?

**Comment by jakob-r** [comment]
We are currently working on `mlr3mbo` but don't expect a CRAN release soon. @mb706 has written a wrapper for mlrMBO and maybe can give you some details.

**Comment by mb706** [comment]
The package in question is https://github.com/mb706/mlrintermbo , it is not well tested yet but I will try to improve it. Install it using `remotes::install_github("mb706/mlrintermbo")` and report issues there if you have any problems or questions.

Using `mlr3` with `mlrMBO` directly unfortunately does *not* work, because `mlr3` interferes with the old `mlr`. `mlrintermbo` jumps through quite a few hoops to avoid this conflict.

**Comment by pabuta88** [comment]
@mb706  Thank you very much for your quick reply and the link! I will try it :-)
