### ISSUE TITLE
Not able to do automated feature selection within resampling loop

### ISSUE THREAD

**Issue by adam2o1o** [mlr-org/mlr3#506]
Hi,

I'm trying to use mlr3 to do some benchmarking and comparisions between classification tasks using different feature sets using `benchmark_grid.` For one of the tasks, I require a feature selection within cross validation, but there isn't any functionality to do that yet. 

I've read in the documentation (https://mlr3book.mlr-org.com/nested-resampling.html):
> the mlr3filters::AutoSelect class (not yet implemented)

Was wondering when will this be implemented?

Thanks

**Comment by mllg** [comment]
You can create a pipeline with a feature filter, see https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_filter.html.

Not sure if the AutoSelect class is still needed.

**Comment by mllg** [comment]
Also see this gallery post: https://mlr3gallery.mlr-org.com/posts/2020-03-11-mlr3pipelines-tutorial-german-credit/.

**Comment by berndbischl** [comment]
> Not sure if the AutoSelect class is still needed.

It is not there and it is not needed. What was ever its intended purpose?

* in order to simply calculate filter scores, use mlr3filter:::Filter$calculate, with these you can now threshold manually and use mlr3:::Task$filter to filter down features.

* if you want to connect a Filter with a Learner, use mlr3pipelines. 
flt("anova") >> lrn("classif.svm")

* these pipelines can now be tuned with mlr3tuning, in the normal manner. You can also use the AutoTuner class from mlr3tuning for simpe nested resampling, which you will probably need in your benchmark. 

----> All is there, since longer. Please tell us if you are still missing something, also in terms of examples or docs. Otherwise we should closer here

**Comment by berndbischl** [comment]
> Not sure if the AutoSelect class is still needed.

A short PS after looking at the book. The AutoSelect class was intended for nested resampling together with FEATURE WRAPPERS not filters, so stuff that really operates on a binary search space. See mlr3fswrap.

**Comment by adam2o1o** [comment]
I see, so you would link the filter to the learner. Thanks both for your help - that answers my question
