### ISSUE TITLE
Stratification censoring rates

### ISSUE THREAD

**Issue by bommert** [mlr-org/mlr3#577]
I'm trying to perform resampling such that the censoring rate in each cross validation fold is roughly identical. I tried to do this with stratification on the status variable, but the censoring rates were very different from each other. Can you please guide me on how to achieve this?

```
library(mlr3)
library(mlr3proba)
set.seed(1)
task = tsk("grace")
task$col_roles$stratum = "status"
resampling = rsmp("cv", folds = 10)
resampling$instantiate(task)
abc = cbind(resampling$instance, s = task$data()[["status"]])
abc[, list(n.total = .N, n.event = sum(s)), by = "fold"]
```
Output:
```
    fold n.total n.event
 1:    1     101      19
 2:    2     101      25
 3:    3     101      29
 4:    4     101      28
 5:    5     100      28
 6:    6     100      32
 7:    7      99      36
 8:    8      99      43
 9:    9      99      39
10:   10      99      45
```

**Comment by mb706** [comment]
The problem is that `resampling$instance` is not ordered by row ID, but by CV fold, so cbinding like this does not assign every item of `s` the correct fold:
```r
> resampling$instance
      row_id fold
   1:      3    1
   2:     13    1
   3:     19    1
   4:     24    1
   5:     32    1
  ---            
 996:    922   10
 997:    927   10
 998:    934   10
 999:    935   10
1000:    974   10
```
If you use the correct row of `status` for every fold you see that the test sets are indeed stratified:
```r
abc = cbind(resampling$instance, s = task$data(rows = resampling$instance$row_id)[["status"]])
abc[, list(n.total = .N, n.event = sum(s)), by = "fold"]
```
```
    fold n.total n.event
 1:    1     101      33
 2:    2     101      33
 3:    3     101      33
 4:    4     101      33
 5:    5     100      32
 6:    6     100      32
 7:    7      99      32
 8:    8      99      32
 9:    9      99      32
10:   10      99      32
```
(Also note that it is incidental that the CV resampling stores the test sets in a data.table like this, other resampling methods have a different format so there the way to get folds would be different. I believe the canonical way to get training and test sets is through `$training_set()` and `$test_set()`)

**Comment by bommert** [comment]
Thank you for the explanation and helpful comments!
