### ISSUE TITLE
when do we define class-methods not inside the R6 class?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#69]
i know, not really an issue, but this does not seem to be clear. so should we define methods (sometimes) outside?

@pfistfl @mllg @zzawadz 

i am really unsure if i see an advantage here. but as some people started doing this, files in mlr3pipelines became messy

**Comment by mllg** [comment]
If you define the methods as functions outside of the class, ...

* ... they get properly byte compiled and you save some runtime because the JIT is not triggered for each instance (but you have an extra function call, so this does not make sense for very simple functions like one-liners).
* ... they can be better tested, as you don't have to construct the complete object first.
* ... R CMD check gives less false positives about missing imports of imported packages (don't ask).
* ... the class is still pretty compact and you can get a quick overview over what is implemented (but you could also use folds in your editor instead)

In the end, it is a matter of taste.

**Comment by berndbischl** [comment]
i would rather discourage that except for really larger functions.

at least i would like to have a very consitent naming scheme then. class_method? and the function are always defined below the class?

**Comment by mllg** [comment]
> at least i would like to have a very consitent naming scheme then. class_method? and the function are always defined below the class?

So just like in https://github.com/mlr-org/mlr3/blob/master/R/Task.R ?

**Comment by berndbischl** [comment]
> So just like in https://github.com/mlr-org/mlr3/blob/master/R/Task.R ?

i guess that is fine with me and seems readable. but we should collect this stuff. do we have a style doc now?

**Comment by pat-s** [comment]
> do we have a style doc now?

And once we have it, where do we place it? I would vote for the website since its a document that applies to all repos?

**Comment by zzawadz** [comment]
I like the idea of `classname_method` for methods defined outside the class.

**Comment by berndbischl** [comment]
> But still I would like to be able to define methods outside the class

well thats fine, but can you argue "why" :)
